# Data Normalization

In [1]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

In [2]:
df_cars = pd.DataFrame([[120000, 11], [250000, 11.5], [175000, 15.8], [350000, 17], [400000, 10]],
                       columns=['odometer_reading', 'fuel_economy'])
print(df_cars)

   odometer_reading  fuel_economy
0            120000          11.0
1            250000          11.5
2            175000          15.8
3            350000          17.0
4            400000          10.0

In [3]:
def min_max_scaling(df):
    # copy the dataframe
    df_norm = df.copy()
    # apply min-max scaling
    for column in df_norm.columns:
        print(column)
        df_norm[column] = (df_norm[column] - df_norm[column].min()) / (df_norm[column].max() - df_norm[column].min())
        #print( df_norm[column] )
    return df_norm

# call the min_max_scaling function
df_cars_normalized = min_max_scaling(df_cars)

df_cars_normalized

odometer_reading
fuel_economy

   odometer_reading  fuel_economy
0          0.000000      0.142857
1          0.464286      0.214286
2          0.196429      0.828571
3          0.821429      1.000000
4          1.000000      0.000000

In [4]:
# create a scaler object
scaler = MinMaxScaler()
# fit and transform the data
df_norm = pd.DataFrame(scaler.fit_transform(df_cars), columns=df_cars.columns)

df_norm

   odometer_reading  fuel_economy
0          0.000000      0.142857
1          0.464286      0.214286
2          0.196429      0.828571
3          0.821429      1.000000
4          1.000000      0.000000

In [5]:
#apply the z-score method in Pandas using the .mean() and .std() methods
def z_score(df):
    # copy the dataframe
    df_std = df.copy()
    # apply the z-score method
    for column in df_std.columns:
        df_std[column] = (df_std[column] - df_std[column].mean()) / df_std[column].std()

    return df_std

# call the z_score function
df_cars_standardized = z_score(df_cars)
df_cars_standardized

   odometer_reading  fuel_economy
0         -1.189512     -0.659120
1         -0.077019     -0.499139
2         -0.718842      0.876693
3          0.778745      1.260647
4          1.206628     -0.979081

In [6]:
from sklearn.preprocessing import StandardScaler

# create a scaler object
std_scaler = StandardScaler()
std_scaler
# fit and transform the data
df_std = pd.DataFrame(std_scaler.fit_transform(df_cars), columns=df_cars.columns)

df_std

   odometer_reading  fuel_economy
0         -1.329915     -0.736918
1         -0.086110     -0.558055
2         -0.803690      0.980173
3          0.870664      1.409446
4          1.349051     -1.094646

Alternatively, we can use the StandardScaler class available in the Scikit-learn library to perform the z-score. First, we create a standard_scaler object. Then, we calculate the parameters of the transformation (in this case the mean and the standard deviation) using the .fit() method. Next, we call the .transform() method to apply the standardization to the data frame.