In [2]:
# from customer transaction view we created, now we visualize the data
import pandas as pd
from sqlalchemy import create_engine

In [3]:
engine = create_engine("mysql+pymysql://root:mihir@localhost:3306/project1")

In [4]:
df = pd.read_sql("SELECT * FROM customers_transactions", engine)
df.head()

,customer_id,first_name,last_name,gender,birthdate,home_location,home_country,first_join_date,booking_id,session_id,created_at,payment_method,payment_status,promo_code,promo_amount,shipment_fee,total_amount,shipment_date_limit
0,65599,Fathonah,Anggraini,F,2006-11-09,Jakarta Raya,Indonesia,2018-07-28,73cb3973-318c-4af3-97e6-cd4e654785ac,bb491696-afb7-470d-b0b3-424e713235de,2022-06-25T17:33:51.232916Z,Credit Card,Success,WEEKENDMANTAP,5940.0,5000.0,151012.0,2022-06-30T12:54:48.611560Z
1,65599,Fathonah,Anggraini,F,2006-11-09,Jakarta Raya,Indonesia,2018-07-28,7d9d4644-5f03-44d2-a25a-1db652f8727f,288d431e-ae43-4967-8e37-46c7c93ed327,2022-05-28T17:01:57.232916Z,Credit Card,Success,NaN,0.0,50000.0,294617.0,2022-05-30T20:48:42.508772Z
2,65599,Fathonah,Anggraini,F,2006-11-09,Jakarta Raya,Indonesia,2018-07-28,cfe37eef-322b-4d06-a6f8-200102492dc4,50264952-f487-4490-8943-920955cb9ceb,2022-04-30T17:24:00.232916Z,Credit Card,Success,NaN,0.0,10000.0,2404786.0,2022-05-02T22:11:22.664954Z
3,65599,Fathonah,Anggraini,F,2006-11-09,Jakarta Raya,Indonesia,2018-07-28,78d4758a-62c2-4e78-b9d7-aaa4018a8d58,16ed5e63-0e38-4001-84c7-3c84aa6d7b4c,2022-04-02T18:00:36.232916Z,Credit Card,Success,WEEKENDMANTAP,8239.0,0.0,83016.0,2022-04-07T22:10:25.825055Z
4,65599,Fathonah,Anggraini,F,2006-11-09,Jakarta Raya,Indonesia,2018-07-28,7f66ac88-c2b6-4c91-8072-fd44c7880943,4f489d97-4ecb-4640-9e9b-e2bcdbf7de9e,2022-03-05T18:28:27.232916Z,LinkAja,Success,WEEKENDSERU,1895.0,0.0,257774.0,2022-03-07T11:40:38.848739Z

In [5]:
df.shape

(901879, 18)

In [6]:
df.info()          # dtypes, nulls per column

<class 'pandas.DataFrame'>
RangeIndex: 901879 entries, 0 to 901878
Data columns (total 18 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   customer_id          901879 non-null  int64
 1   first_name           901879 non-null  str
 2   last_name            901879 non-null  str
 3   gender               901879 non-null  str
 4   birthdate            901879 non-null  str
 5   home_location        901879 non-null  str
 6   home_country         901879 non-null  str
 7   first_join_date      901879 non-null  str
 8   booking_id           852584 non-null  str
 9   session_id           852584 non-null  str
 10  created_at           852584 non-null  str
 11  payment_method       852584 non-null  str
 12  payment_status       852584 non-null  str
 13  promo_code           326536 non-null  str
 14  promo_amount         852584 non-null  float64
 15  shipment_fee         852584 non-null  float64
 16  total_amount         852584 non-null  float64
 17  shipment_date_limit  852584 non-null  str
dtypes: float64(3), int64(1), str(14)
memory usage: 123.9 MB

In [10]:
df.isnull().sum()

customer_id                 0
first_name                  0
last_name                   0
gender                      0
birthdate                   0
home_location               0
home_country                0
first_join_date             0
booking_id              49295
session_id              49295
created_at              49295
payment_method          49295
payment_status          49295
promo_code             575343
promo_amount            49295
shipment_fee            49295
total_amount            49295
shipment_date_limit     49295
dtype: int64

In [8]:
df.describe()

         customer_id   promo_amount   shipment_fee  total_amount
count  901879.000000  852584.000000  852584.000000  8.525840e+05
mean    49858.679122    2042.077949    9189.675152  5.499165e+05
std     28987.141771    3063.481424    9377.856335  8.153761e+05
min         1.000000       0.000000       0.000000  1.089800e+04
25%     24594.000000       0.000000       0.000000  2.037938e+05
50%     49667.000000       0.000000   10000.000000  3.029890e+05
75%     74964.000000    3993.000000   10000.000000  5.147022e+05
max    100000.000000   24519.000000   50000.000000  2.350449e+07

In [9]:
df['customer_id'].nunique()

100000